### ISSUE TITLE
无法登录到演示项目中

### ISSUE THREAD

**Issue by makk909** [zhaoyang21cn/iLiveSDK_Web_Suixinbo#2]
你好

我已经使用Postman工具上的登录和注册API成功部署了后端，但是将后端与演示项目链接起来，注册功能完美而不是登录。它给我这个错误  http://prntscr.com/gkjlzt   现在不知道是什么问题，这个错误似乎在实际的iLiveSDK。你能帮我一下吗

谢谢..！！

**Comment by jepsonyang** [comment]
有问题请加QQ群咨询: 594923937

**Comment by makk909** [comment]
谢谢你快速恢复，但是那是什么？我该如何补充？

**Comment by jepsonyang** [comment]
这是错误码表https://github.com/zhaoyang21cn/iLiveSDK_Android_Suixinbo/blob/master/doc/ILiveSDK/error.md

你这个错误码是IMSDK的错误码，请在里面查下

**Comment by makk909** [comment]
根据错误，它说公钥的长度是0，但我确实有有效的公钥和私钥已经上传到我的服务器上。

**Comment by jepsonyang** [comment]
加群询问，群里有人负责答疑的

**Comment by makk909** [comment]
如何将群组标记为我的问题？
